SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK A
LEFT JOIN AUTHOR B ON A.AUTHOR_ID=B.AUTHOR_ID
LEFT JOIN BOOK_SALES C ON A.BOOK_ID=C.BOOK_ID AND DATE_FORMAT(SALES_DATE, '%Y-%m')='2022-01'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;