SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES 
           FROM BOOK_SALES 
           WHERE SALES_DATE LIKE '2022-01%'
           GROUP BY BOOK_ID) BS ON BS.BOOK_ID = B.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;