# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO 
# WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
#                           FROM ITEM_TREE)
                          
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;