# 상품코드 별 (매출액 = 판매가 * 판매량) 합계 출력
# 매출액 기준 내림차순, 상품코드 오름차순

SELECT B.PRODUCT_CODE, SUM(A.SALES_AMOUNT*B.PRICE) AS SALES
FROM OFFLINE_SALE A
LEFT JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;