# 중성화 X -> 중성화 O
# 아이디순

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR  O.SEX_UPON_OUTCOME LIKE'Neutered%') AND I.SEX_UPON_INTAKE LIKE ('Intact%')
ORDER BY ANIMAL_ID;