# 들어올 때 중성화 X, 나갈 때 중성화 O
# 아이디 순

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID=I.ANIMAL_ID
WHERE (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%') AND I.SEX_UPON_INTAKE LIKE ('Intact%')
ORDER BY ANIMAL_ID;