# Spayed 중성화 O
# Intact 중성화 X

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O 
LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE ((O.SEX_UPON_OUTCOME LIKE "Spayed%")|(O.SEX_UPON_OUTCOME LIKE "Neutered%"))
        & 
      (I.SEX_UPON_INTAKE LIKE "Intact%")
ORDER BY ANIMAL_ID ASC;