# 서울에 위치한 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수를 조회
# 리뷰 평균점수는 소수점 세 번째 자리에서 반올림
# 평균점수 내림차순, 즐겨찾기수 내림차순

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE
FROM REST_INFO A
LEFT JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
          FROM REST_REVIEW
          GROUP BY REST_ID) B ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE ("서울%") AND SCORE IS NOT NULL
ORDER BY B.SCORE DESC, A.FAVORITES DESC;