# 년, 월, 성별 별로 상품을 구매한 회원수 집계
# 년, 월, 성별 기준으로 오름차순
# 성별 정보가 없는 경우 결과에서 제외

SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER, 
       COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A
LEFT JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE), B.GENDER
ORDER BY YEAR, MONTH, GENDER
