# 대여시작일 : 2022-09 && 30일 이상이면 장기대여 아니면 단기대여 컬럼 추가 
# 대여 기록 ID 내림차순

SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE, 
    CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '장기 대여'
         ELSE '단기 대여' END AS RENTAL_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE)=9
ORDER BY HISTORY_ID DESC;