# 평균 대여 기간 >= 7 (자동차 ID, 평균 대여 기간 - AVERAGE_DURATION)
# 평균 대여 기간 : 소수점 두번째 반올림
# 평균 대여 기간 내림차순, 자동차 ID 내림차순

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;