# 종류별 물고기의 이름과 잡은 수
# 잡은 수 기준 내림차순
 
SELECT COUNT(A.ID) AS FISH_COUNT, B.FISH_NAME
FROM FISH_INFO A
LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME 
ORDER BY FISH_COUNT DESC;