# 2021 가입 && 상품 구매 / 2021 가입 전체 회원
# 소수점 두번째자리 반올림 
# 년 기준 오름차순, 월 기준 오름차순

SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1)  AS PUCHASED_RATIO
FROM ONLINE_SALE A
LEFT JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE YEAR(B.JOINED)=2021
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR, MONTH;