# 2022-10-16일에 대여 중인 자동차 -> 대여중/대여 가능 (AVAILABILITY)
# 반납 날짜가 2022-10-16일이어도 대여중
# CAR_ID 내림차순

SELECT DISTINCT A.CAR_ID, CASE WHEN B.AVAILABLE IS NULL THEN '대여 가능'
                                ELSE B.AVAILABLE END AS AVAILABLE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN (SELECT CAR_ID, '대여중' AS AVAILABLE
             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE END_DATE>='2022-10-16' AND START_DATE<='2022-10-16') B ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC