# 생산일자 = 202205 
# (PRODUCT_ID, 총매출)별로 총매출 조회
# 총매출 DESC, PRODUCT_ID ASC

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O
LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE)=2022 AND MONTH(PRODUCE_DATE)=5 AND P.PRODUCT_ID IS NOT NULL
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;