# 7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량
# 큰 순서대로 상위 3개 맛 조회 (Limit 3)

SELECT A.FLAVOR
FROM (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) AS SUM1
     FROM JULY A
     GROUP BY FLAVOR) A
LEFT JOIN (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) AS SUM2
     FROM FIRST_HALF A
     GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
ORDER BY A.SUM1 + B.SUM2 DESC
LIMIT 3;