# 2022-04-13 취소되지 않은 CS 진료 예약 내역 조회
# 진료예약일시 오름차순
# 


SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, D.MCDP_CD,  D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS' AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD ASC;