# 생일 3월 & 여성
# 전화번호 != NULL
# ID 오름차순

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER='W' AND MONTH(DATE_OF_BIRTH)=03 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;