# 완료된 중고 거래 총금액 >= 70 회원
# 거래금액 ASC

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID=B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME
HAVING SUM(A.PRICE)>=700000
ORDER BY TOTAL_SALES;