SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R 
LEFT JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID
                     FROM (SELECT MEMBER_ID, DENSE_RANK() OVER(ORDER BY COUNT(*) DESC) AS RN
                          FROM REST_REVIEW
                          GROUP BY MEMBER_ID
                          ) T
                      WHERE RN = 1)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;