SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE) IN (8,9,10)
        AND CAR_ID IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                     GROUP BY CAR_ID
                       HAVING COUNT(HISTORY_ID)>4)
GROUP BY MONTH, CAR_ID
HAVING COUNT(*)>0
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;