# 2022.08 ~ 2022.10 
# 시작일 기준 대여 횟수 5회 이상
# 해당 기간 월별 자동차 ID별 총 대여 횟수(RECORDS)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORES
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE YEAR(START_DATE)=2022 AND (MONTH(START_DATE) IN (8,9,10))
                GROUP BY CAR_ID
                HAVING COUNT(HISTORY_ID)>=5) 
    AND YEAR(START_DATE)=2022 AND (MONTH(START_DATE) IN (8,9,10))
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC