# 2022년도 가장 높은 점수 사원
# 상,하반기 점수 합

SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
LEFT JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
LEFT JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;