# 부서별 평균 연봉(첫째자리 반올림)
# 연봉 내림차순

SELECT B.DEPT_ID, B.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES A
LEFT JOIN HR_DEPARTMENT B ON A.DEPT_ID = B.DEPT_ID
GROUP BY B.DEPT_ID, B.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;