# 조회수가 가장 높은 중고거래 게시물 첨부파일 경로 조회
# FILE ID 내림차순
# 기본 경로 /home/grep/src/

SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A
LEFT JOIN USED_GOODS_BOARD B ON A.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS)
                  FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;