# 2022-01 카테고리별 도서 판매량 합산
# 카테고리명 오름차순

SELECT B.CATEGORY, SUM(A.SALES) AS TOTAL_SALES
FROM BOOK_SALES A 
LEFT JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m')='2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY;