SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT CASE WHEN LENGTH<=10 THEN 10
             WHEN LENGTH IS NULL THEN 10
             ELSE LENGTH END AS LENGTH, ID, FISH_TYPE
        FROM FISH_INFO) AS A
GROUP BY A.FISH_TYPE
HAVING AVG(LENGTH)>=33
ORDER BY FISH_TYPE ASC;