# 만원 단위의 가격대 별로 상품 개수 출력
# 가격대 오름차순

SELECT A.PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM (SELECT PRODUCT_ID, PRICE - PRICE%10000 AS PRICE_GROUP
      FROM PRODUCT) A
GROUP BY A.PRICE_GROUP
ORDER BY A.PRICE_GROUP;